# Site settings
title: "The Phil Project | I'm Phil. It's my project."
description: "I'm Phil. It's my project."
url: "http://www.thephilproject.com"
author:
  name: "Philip Lee"
  email: "phil@thephilproject.com"
  url: "http://www.thephilproject.com"

# Build settings
baseurl: / # Change this to your relative path (ex: /blog/), or leave just a /
markdown: redcarpet
source: .
destination: ./_site
permalink: /:title
paginate: 8
paginate_path: /page:num/
gems: [jekyll-paginate]

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
version: "1.1.0"

# Options
custom_header: false
custom_nav_footer: false
reverse: false
